[2022-04-19 15:31:30,617] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.parseJsonFile 2022-04-19T15:30:56.246116+00:00 [queued]>
[2022-04-19 15:31:30,624] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.parseJsonFile 2022-04-19T15:30:56.246116+00:00 [queued]>
[2022-04-19 15:31:30,624] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 15:31:30,624] {taskinstance.py:1043} INFO - Starting attempt 2 of 4
[2022-04-19 15:31:30,624] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 15:31:30,632] {taskinstance.py:1063} INFO - Executing <Task(BranchPythonOperator): parseJsonFile> on 2022-04-19T15:30:56.246116+00:00
[2022-04-19 15:31:30,636] {standard_task_runner.py:52} INFO - Started process 582 to run task
[2022-04-19 15:31:30,639] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'parseJsonFile', '2022-04-19T15:30:56.246116+00:00', '--job-id', '241', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmpd_m71606', '--error-file', '/tmp/tmpe8_h6pkw']
[2022-04-19 15:31:30,641] {standard_task_runner.py:77} INFO - Job 241: Subtask parseJsonFile
[2022-04-19 15:31:30,668] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.parseJsonFile 2022-04-19T15:30:56.246116+00:00 [running]> on host 6a1987cfb959
[2022-04-19 15:31:30,692] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=anhlbt
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=parseJsonFile
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T15:30:56.246116+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-19T15:30:56.246116+00:00
[2022-04-19 15:31:30,702] {s3.py:793} INFO - Downloading source S3 file from Bucket airflow-raw/data with path countyData.json
[2022-04-19 15:31:30,702] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-04-19 15:31:30,703] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-19 15:31:30,704] {base_aws.py:171} INFO - Credentials retrieved from extra_config['s3_config_file']
[2022-04-19 15:31:30,704] {base_aws.py:81} INFO - Creating session with aws_access_key_id=AKIA2RNRZHIUSS5EYBCG region_name=None
[2022-04-19 15:31:30,713] {base_aws.py:151} INFO - role_arn is None
[2022-04-19 15:31:30,738] {taskinstance.py:1455} ERROR - Parameter validation failed:
Invalid bucket name "airflow-raw/data": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 324, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dagRun.py", line 157, in readJsonData
    local_path=path
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 61, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 795, in download_file
    if not self.check_for_key(key, bucket_name):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 61, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 314, in check_for_key
    self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 649, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 695, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/client.py", line 727, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/botocore/handlers.py", line 210, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "airflow-raw/data": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:s3:[a-z\-0-9]+:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
[2022-04-19 15:31:30,740] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=analyze_json_data, task_id=parseJsonFile, execution_date=20220419T153056, start_date=20220419T153130, end_date=20220419T153130
[2022-04-19 15:31:30,769] {local_task_job.py:146} INFO - Task exited with return code 1
