[2022-04-19 15:32:33,017] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.parseJsonFile 2022-04-19T15:30:56.246116+00:00 [queued]>
[2022-04-19 15:32:33,024] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.parseJsonFile 2022-04-19T15:30:56.246116+00:00 [queued]>
[2022-04-19 15:32:33,025] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 15:32:33,025] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2022-04-19 15:32:33,025] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 15:32:33,035] {taskinstance.py:1063} INFO - Executing <Task(BranchPythonOperator): parseJsonFile> on 2022-04-19T15:30:56.246116+00:00
[2022-04-19 15:32:33,039] {standard_task_runner.py:52} INFO - Started process 856 to run task
[2022-04-19 15:32:33,041] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'parseJsonFile', '2022-04-19T15:30:56.246116+00:00', '--job-id', '243', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmpm5xzkfxx', '--error-file', '/tmp/tmpu6jrcqee']
[2022-04-19 15:32:33,044] {standard_task_runner.py:77} INFO - Job 243: Subtask parseJsonFile
[2022-04-19 15:32:33,069] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.parseJsonFile 2022-04-19T15:30:56.246116+00:00 [running]> on host 6a1987cfb959
[2022-04-19 15:32:33,095] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Renato_Otescu
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=parseJsonFile
AIRFLOW_CTX_EXECUTION_DATE=2022-04-19T15:30:56.246116+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-19T15:30:56.246116+00:00
[2022-04-19 15:32:33,109] {s3.py:793} INFO - Downloading source S3 file from Bucket airflow-raw with path countyData.json
[2022-04-19 15:32:33,109] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-04-19 15:32:33,110] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-19 15:32:33,110] {base_aws.py:171} INFO - Credentials retrieved from extra_config['s3_config_file']
[2022-04-19 15:32:33,110] {base_aws.py:81} INFO - Creating session with aws_access_key_id=AKIA2RNRZHIUSS5EYBCG region_name=None
[2022-04-19 15:32:33,118] {base_aws.py:151} INFO - role_arn is None
[2022-04-19 15:32:33,784] {taskinstance.py:1455} ERROR - The source file in Bucket airflow-raw with path countyData.json does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 324, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dagRun.py", line 157, in readJsonData
    local_path=path
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 61, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 796, in download_file
    raise AirflowException(f'The source file in Bucket {bucket_name} with path {key} does not exist')
airflow.exceptions.AirflowException: The source file in Bucket airflow-raw with path countyData.json does not exist
[2022-04-19 15:32:33,786] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=analyze_json_data, task_id=parseJsonFile, execution_date=20220419T153056, start_date=20220419T153233, end_date=20220419T153233
[2022-04-19 15:32:33,813] {local_task_job.py:146} INFO - Task exited with return code 1
