[2022-04-19 14:39:06,940] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.saveToDB 2022-04-18T00:00:00+00:00 [queued]>
[2022-04-19 14:39:06,952] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.saveToDB 2022-04-18T00:00:00+00:00 [queued]>
[2022-04-19 14:39:06,952] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 14:39:06,952] {taskinstance.py:1043} INFO - Starting attempt 2 of 4
[2022-04-19 14:39:06,952] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-19 14:39:06,958] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): saveToDB> on 2022-04-18T00:00:00+00:00
[2022-04-19 14:39:06,961] {standard_task_runner.py:52} INFO - Started process 686 to run task
[2022-04-19 14:39:06,963] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'saveToDB', '2022-04-18T00:00:00+00:00', '--job-id', '217', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmp88vel97y', '--error-file', '/tmp/tmpqla4b9q6']
[2022-04-19 14:39:06,965] {standard_task_runner.py:77} INFO - Job 217: Subtask saveToDB
[2022-04-19 14:39:06,996] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.saveToDB 2022-04-18T00:00:00+00:00 [running]> on host 79776f5a39da
[2022-04-19 14:39:07,025] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Renato_Otescu
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=saveToDB
AIRFLOW_CTX_EXECUTION_DATE=2022-04-18T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-18T00:00:00+00:00
[2022-04-19 14:39:07,051] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-04-19 14:39:07,051] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-19 14:39:07,052] {base_aws.py:171} INFO - Credentials retrieved from extra_config['s3_config_file']
[2022-04-19 14:39:07,052] {base_aws.py:81} INFO - Creating session with aws_access_key_id=AKIA2RNRZHIUSS5EYBCG region_name=None
[2022-04-19 14:39:07,060] {base_aws.py:151} INFO - role_arn is None
[2022-04-19 14:39:08,086] {taskinstance.py:1455} ERROR - Cannot COPY into nonexistent table vn
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dagRun.py", line 270, in uploadToDB
    cursor.execute(sql)
psycopg2.errors.InternalError_: Cannot COPY into nonexistent table vn

[2022-04-19 14:39:08,088] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=analyze_json_data, task_id=saveToDB, execution_date=20220418T000000, start_date=20220419T143906, end_date=20220419T143908
[2022-04-19 14:39:08,135] {local_task_job.py:146} INFO - Task exited with return code 1
