[2022-04-17 01:56:11,370] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.saveToDB 2022-04-16T00:00:00+00:00 [queued]>
[2022-04-17 01:56:11,377] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: analyze_json_data.saveToDB 2022-04-16T00:00:00+00:00 [queued]>
[2022-04-17 01:56:11,377] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-17 01:56:11,377] {taskinstance.py:1043} INFO - Starting attempt 4 of 4
[2022-04-17 01:56:11,377] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-17 01:56:11,386] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): saveToDB> on 2022-04-16T00:00:00+00:00
[2022-04-17 01:56:11,390] {standard_task_runner.py:52} INFO - Started process 967 to run task
[2022-04-17 01:56:11,393] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'analyze_json_data', 'saveToDB', '2022-04-16T00:00:00+00:00', '--job-id', '192', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dagRun.py', '--cfg-path', '/tmp/tmpg58k65bo', '--error-file', '/tmp/tmpyjiy408z']
[2022-04-17 01:56:11,395] {standard_task_runner.py:77} INFO - Job 192: Subtask saveToDB
[2022-04-17 01:56:11,426] {logging_mixin.py:104} INFO - Running <TaskInstance: analyze_json_data.saveToDB 2022-04-16T00:00:00+00:00 [running]> on host 184ae5fa8a0d
[2022-04-17 01:56:11,455] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Renato_Otescu
AIRFLOW_CTX_DAG_ID=analyze_json_data
AIRFLOW_CTX_TASK_ID=saveToDB
AIRFLOW_CTX_EXECUTION_DATE=2022-04-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-16T00:00:00+00:00
[2022-04-17 01:56:11,482] {base_aws.py:362} INFO - Airflow Connection: aws_conn_id=aws_default
[2022-04-17 01:56:11,482] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-17 01:56:11,482] {base_aws.py:171} INFO - Credentials retrieved from extra_config['s3_config_file']
[2022-04-17 01:56:11,483] {base_aws.py:81} INFO - Creating session with aws_access_key_id=AKIA2RNRZHIUSS5EYBCG region_name=None
[2022-04-17 01:56:11,490] {base_aws.py:151} INFO - role_arn is None
[2022-04-17 01:56:12,498] {taskinstance.py:1455} ERROR - Cannot COPY into nonexistent table counties
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dagRun.py", line 269, in uploadToDB
    cursor.execute(sql)
psycopg2.errors.InternalError_: Cannot COPY into nonexistent table counties

[2022-04-17 01:56:12,500] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=analyze_json_data, task_id=saveToDB, execution_date=20220416T000000, start_date=20220417T015611, end_date=20220417T015612
[2022-04-17 01:56:12,526] {local_task_job.py:146} INFO - Task exited with return code 1
